apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service-app
        image: user-service:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: mysql.user
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: mysql.password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: mysql.database
        ports:
        - containerPort: 3000
      - name: user-service-mysql
        image: mysql:latest
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: mysql.user
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: mysql.password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: user-service-config
                key: mysql.database
        ports:
        - containerPort: 3306
